/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmDisparityMap_hpp__
#define __ZcmDisparityMap_hpp__

#include <vector>
#include "ZcmService.hpp"


/**
 * @struct ZcmDisparityMap
 * @brief Сообщение содержит информацию
 * @var jpeg_frame
 * @brief кадр левой камеры, которому соответствует данная карта диспаратности
 * @var height
 * @brief высота в пикселях карты диспаратности
 * @var width
 * @brief ширина в пикселях карты диспаратности
 * @var size
 * @brief количество пикселей в карте диспаратности
 * @var scale
 * @brief коэффициент, на который необходимо умножить карту диспаратности для получения реального значения
 * @var padding
 * @brief массив, содержащий значения отступов от верхней, првой, нижней, левой границ изображений соответственно.
 * Все значения приведены в пикселях
 * @var disp
 * @brief карта диспаратности в виде одномерного массива с глубиной 16 бит
 * @var R
 * @brief массив из трёх значений поворота камеры (в радианах) относительно линии горизонта, перпендикуляра к опорной поверхности и лучу в бесконечную плоскость кадра соответственно
 * @var T
 * @brief массив из трёх значений смещения камеры (в метрах) относительно нашего центра координат по горизонтальному смещению, вертикальному смещению и смещению в глубину соответственно
 * @var Q
 * @brief матрица реконструкции 4x4 (opencv perspective transformation matrix)
 *
 */
class ZcmDisparityMap
{
    public:
        ZcmService service;

        int32_t    height;

        int32_t    width;

        int32_t    size;

        double     scale;

        int32_t    padding[4];

        std::vector< int16_t > disp;

        double     Q[16];

        double     R[3];

        double     T[3];

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmDisparityMap() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmDisparityMap"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmDisparityMap::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmDisparityMap::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmDisparityMap::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmDisparityMap::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmDisparityMap::getTypeName()
{
    return "ZcmDisparityMap";
}

int ZcmDisparityMap::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->scale, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->padding[0], 4);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->size > 0) {
        thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->disp[0], this->size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->Q[0], 16);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R[0], 3);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->T[0], 3);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmDisparityMap::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->size, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->scale, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->padding[0], 4);
    if(thislen < 0) return thislen; else pos += thislen;

    if(this->size > 0) {
        this->disp.resize(this->size);
        thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->disp[0], this->size);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->Q[0], 16);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R[0], 3);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->T[0], 3);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmDisparityMap::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 4);
    enc_size += __int16_t_encoded_array_size(NULL, this->size);
    enc_size += __double_encoded_array_size(NULL, 16);
    enc_size += __double_encoded_array_size(NULL, 3);
    enc_size += __double_encoded_array_size(NULL, 3);
    return enc_size;
}

uint64_t ZcmDisparityMap::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmDisparityMap::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmDisparityMap::getHash };

    uint64_t hash = (uint64_t)0xbf7a7c72400a9b13LL +
         ZcmService::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
