/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmFromOduObstacles_hpp__
#define __ZcmFromOduObstacles_hpp__

#include "ZcmService.hpp"


/**
 * @struct ZcmFromOduObstacles
 * @brief Данные о препятствиях от блока обнаружения препятствий
 * @var ZcmFromOduObstacles::DISTANCE_UNDEFINED
 * @brief Признак, что препятствие не обнаружено
 * @var ZcmFromOduObstacles::TYPE_NO_OBSTACLE
 * @brief Нет препятствия
 * @var ZcmFromOduObstacles::TYPE_HUMAN
 * @brief Тип препятствия: человек
 * @var ZcmFromOduObstacles::TYPE_ANIMAL
 * @brief Тип препятствия: животное (кошка, собака)
 * @var ZcmFromOduObstacles::TYPE_TRAIN
 * @brief Тип препятствия: подвижной состав
 * @var ZcmFromOduObstacles::TYPE_BIG
 * @brief Тип препятствия: большой неопределенный объект
 * @var ZcmFromOduObstacles::TYPE_SMALL
 * @brief Тип препятствия: малый неопределенный объект
 * @var ZcmFromOduObstacles::TYPE_AUTO
 * @brief Тип препятствия: автомобиль
 * @var ZcmFromOduObstacles::TYPE_OTHER
 * @brief Тип препятствия: другое
 * @var ZcmFromOduObstacles::red_distance
 * @brief Расстояние до препятствия в красной зоне, дециметр
 * @var ZcmFromOduObstacles::yellow_distance
 * @brief Расстояние до препятствия в желтой зоне, дециметр
 * @var ZcmFromOduObstacles::brown_distance
 * @brief Расстояние до препятствия в коричневой зоне, дециметр
 * @var ZcmFromOduObstacles::vision_distance
 * @brief Расстояние видимости БОП, дециметр
 *
 */
class ZcmFromOduObstacles
{
    public:
        ZcmService service;

        int32_t    red_distance;

        int8_t     red_type;

        int32_t    yellow_distance;

        int8_t     yellow_type;

        int32_t    brown_distance;

        int8_t     brown_type;

        int32_t    vision_distance;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int32_t  DISTANCE_UNDEFINED = 0xFFFF;
        static constexpr int8_t   TYPE_NO_OBSTACLE = 0;
        static constexpr int8_t   TYPE_HUMAN = 1;
        static constexpr int8_t   TYPE_ANIMAL = 2;
        static constexpr int8_t   TYPE_TRAIN = 3;
        static constexpr int8_t   TYPE_BIG = 4;
        static constexpr int8_t   TYPE_SMALL = 5;
        static constexpr int8_t   TYPE_AUTO = 6;
        static constexpr int8_t   TYPE_OTHER = 7;
        #else
        static const     int32_t  DISTANCE_UNDEFINED = 0xFFFF;
        static const     int8_t   TYPE_NO_OBSTACLE = 0;
        static const     int8_t   TYPE_HUMAN = 1;
        static const     int8_t   TYPE_ANIMAL = 2;
        static const     int8_t   TYPE_TRAIN = 3;
        static const     int8_t   TYPE_BIG = 4;
        static const     int8_t   TYPE_SMALL = 5;
        static const     int8_t   TYPE_AUTO = 6;
        static const     int8_t   TYPE_OTHER = 7;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmFromOduObstacles() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmFromOduObstacles"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmFromOduObstacles::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmFromOduObstacles::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmFromOduObstacles::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmFromOduObstacles::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmFromOduObstacles::getTypeName()
{
    return "ZcmFromOduObstacles";
}

int ZcmFromOduObstacles::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->red_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->red_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->yellow_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->yellow_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->brown_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->brown_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->vision_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmFromOduObstacles::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->red_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->red_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->yellow_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->yellow_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->brown_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->brown_type, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->vision_distance, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmFromOduObstacles::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t ZcmFromOduObstacles::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmFromOduObstacles::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmFromOduObstacles::getHash };

    uint64_t hash = (uint64_t)0xe22318f29ced4a83LL +
         ZcmService::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
