/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmLidarScalaFilteredObjectAttributes_hpp__
#define __ZcmLidarScalaFilteredObjectAttributes_hpp__

#include <vector>
#include "ZcmLidarScalaContourPoint.hpp"


/**
 * @struct ZcmLidarScalaFilteredObjectAttributes
 * @brief Отфильтрованные параметры
 * @var ZcmLidarScalaFilteredObjectAttributes::objectAge
 * @brief - количество сканирований на протяжении которых данный объект существует
 * @var ZcmLidarScalaFilteredObjectAttributes::hiddenStatusAge
 * @brief - количество сканирований на протяжении которых данный объект был предсказан
 * @var ZcmLidarScalaFilteredObjectAttributes::dynamicFlagState
 * @brief - динамическое состояние объекта
 * 				 0 - объект в стадии инициализации
 * 				 1 - объект в стадии отслеживания
 * 				 
 * @var ZcmLidarScalaFilteredObjectAttributes::dynamicFlagProperty
 * @brief - динамическое состояние объекта
 * 				1 - dynamic and moving
 * 				2 - dynamic and stopped
 * 				3 - internal
 * 				4 - a priori stationary
 * @var ZcmLidarScalaFilteredObjectAttributes::relativeTimeOfMeasure
 * @brief - время с момента начала измерения (мс)
 * @var ZcmLidarScalaFilteredObjectAttributes::positionClosestObjectPointX
 * @brief - ближайшая точка объекта по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::positionClosestObjectPointY
 * @brief - ближайшая точка объекта по оси Y (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::relativeVelocityX
 * @brief - относительная скорость по оси X (м/с)
 * @var ZcmLidarScalaFilteredObjectAttributes::relativeVelocityY
 * @brief - относительная скорость по оси Y (м/с)
 * @var ZcmLidarScalaFilteredObjectAttributes::relativeVelocitySigmaX
 * @brief - погрешность относительной скорости по оси X (м/с)
 * @var ZcmLidarScalaFilteredObjectAttributes::relativeVelocitySigmaY
 * @brief - погрешность относительной скорости по оси Y (м/с)
 * @var ZcmLidarScalaFilteredObjectAttributes::classification
 * @brief - классификация объекта \n
 * 					0  - Unclassified   \n
 * 					1  - UnknownSmall   \n
 * 					2  - UnknownBig     \n
 * 					3  - Pedestrian    \n
 * 					4  - Bike           \n
 * 					5  - Car            \n
 * 					6  - Truck          \n
 * 					10 - Overdrivable  \n
 * 					11 - Underdrivable  \n
 * 					12 - Bicycle        \n
 * 					15 - Motorbike      \n
 * 					16 - Infrastructure \n
 * @var ZcmLidarScalaFilteredObjectAttributes::classificationQuality
 * @brief - ???
 * @var ZcmLidarScalaFilteredObjectAttributes::classificationAge
 * @brief - количество сканирований на протяжении которых данный объект относится к этому классу
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeX
 * @brief - расстояние до объекта по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeY
 * @brief - расстояние до объекта по оси Y (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeWidth
 * @brief - ширина объекта (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeLength
 * @brief - длина объекта (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeSigmaX
 * @brief - погрешность по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxSizeSigmaY
 * @brief - погрешность по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxOrientation
 * @brief - угол поворота объекта (градусы)
 *  
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxOrientationSigma
 * @brief - погрешность угла поворота объекта (градусы)
 * @var ZcmLidarScalaFilteredObjectAttributes::objectBoxHeight
 * @brief - высота объекта (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointLocation 
 * @brief -  расположение базовой точки объекта \n
 * 				0x0 - CenterOfGravity \n
 * 				0x1 - FrontLeft       \n 
 * 				0x2 - FrontRight      \n 
 * 				0x3 - RearRight       \n
 * 				0x4 - RearLeft        \n
 * 				0x5 - FrontCenter     \n
 * 				0x6 - RightCenter     \n
 * 				0x7 - RearCenter      \n
 * 				0x8 - LeftCenter      \n
 * 				0x9 - ObjectCenter    \n
 * 				0xff - Unknown         
 *  
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointCoordX
 * @brief - Расстояние до базовой точки по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointCoordY
 * @brief - Расстояние до базовой точки по оси Y (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointCoordSigmaX
 * @brief - погрешность расстояния до базовой точки по оси X (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointCoordSigmaY
 * @brief - погрешность расстояния до базовой точки по оси Y (м)
 * @var ZcmLidarScalaFilteredObjectAttributes::referencePointPositionCorrCoeff
 * @brief - ???
 * @var ZcmLidarScalaFilteredObjectAttributes::existenceProbaility
 * @brief - вероятность существования объекта
 * @var ZcmLidarScalaFilteredObjectAttributes::absoluteVelocityX
 * @brief - абсолютное значение скорости по X
 * @var ZcmLidarScalaFilteredObjectAttributes::absoluteVelocityY
 * @brief - абсолютное значение скорости по Y
 * @var ZcmLidarScalaFilteredObjectAttributes::absoluteVelocitySigmaX
 * @brief - погрешность абсолютного значения скорости по X
 * @var ZcmLidarScalaFilteredObjectAttributes::absoluteVelocitySigmaY
 * @brief - погрешность абсолютного значения скорости по Y
 * @var ZcmLidarScalaFilteredObjectAttributes::velocityCorrCoeff
 * @brief - ???
 * @var ZcmLidarScalaFilteredObjectAttributes::accelerationX
 * @brief - ускорение по оси X (м/с2)
 * @var ZcmLidarScalaFilteredObjectAttributes::accelerationY
 * @brief - ускорение по оси Y (м/с2)
 * @var ZcmLidarScalaFilteredObjectAttributes::accelerationSigmaX
 * @brief - погрешность ускорения по оси X (м/с2)
 * @var ZcmLidarScalaFilteredObjectAttributes::accelerationSigmaY
 * @brief - погрешность ускорения по оси Y (м/с2)
 * @var ZcmLidarScalaFilteredObjectAttributes::accelerationCorrCoeff
 * @brief - ???
 * @var ZcmLidarScalaFilteredObjectAttributes::possibleNbOfContourPoints
 * @brief - количество точек контура объекта
 * @var ZcmLidarScalaFilteredObjectAttributes::contourPoints
 * @brief - точки контура объекта
 *
 */
class ZcmLidarScalaFilteredObjectAttributes
{
    public:
        int32_t    objectAge;

        int32_t    hiddenStatusAge;

        int8_t     dynamicFlagState;

        int8_t     dynamicFlagProperty;

        int32_t    relativeTimeOfMeasure;

        float      positionClosestObjectPointX;

        float      positionClosestObjectPointY;

        float      relativeVelocityX;

        float      relativeVelocityY;

        float      relativeVelocitySigmaX;

        float      relativeVelocitySigmaY;

        int16_t    classification;

        int16_t    classificationQuality;

        int32_t    classificationAge;

        float      objectBoxSizeX;

        float      objectBoxSizeY;

        float      objectBoxSizeSigmaX;

        float      objectBoxSizeSigmaY;

        float      objectBoxOrientation;

        float      objectBoxOrientationSigma;

        float      objectBoxHeight;

        int16_t    referencePointLocation;

        float      referencePointCoordX;

        float      referencePointCoordY;

        float      referencePointCoordSigmaX;

        float      referencePointCoordSigmaY;

        int16_t    referencePointPositionCorrCoeff;

        float      existenceProbaility;

        float      absoluteVelocityX;

        float      absoluteVelocityY;

        float      absoluteVelocitySigmaX;

        float      absoluteVelocitySigmaY;

        int16_t    velocityCorrCoeff;

        float      accelerationX;

        float      accelerationY;

        float      accelerationSigmaX;

        float      accelerationSigmaY;

        int16_t    accelerationCorrCoeff;

        int16_t    possibleNbOfContourPoints;

        std::vector< ZcmLidarScalaContourPoint > contourPoints;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmLidarScalaFilteredObjectAttributes() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmLidarScalaFilteredObjectAttributes"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmLidarScalaFilteredObjectAttributes::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarScalaFilteredObjectAttributes::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmLidarScalaFilteredObjectAttributes::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmLidarScalaFilteredObjectAttributes::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmLidarScalaFilteredObjectAttributes::getTypeName()
{
    return "ZcmLidarScalaFilteredObjectAttributes";
}

int ZcmLidarScalaFilteredObjectAttributes::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->objectAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->hiddenStatusAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->dynamicFlagState, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->dynamicFlagProperty, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->relativeTimeOfMeasure, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->positionClosestObjectPointX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->positionClosestObjectPointY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocityX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocityY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocitySigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocitySigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->classification, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->classificationQuality, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->classificationAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxOrientation, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxOrientationSigma, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->objectBoxHeight, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointLocation, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->referencePointPositionCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->existenceProbaility, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocityX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocityY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocitySigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocitySigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->velocityCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->accelerationX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->accelerationY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->accelerationSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->accelerationSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->accelerationCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_encode_array(buf, offset + pos, maxlen - pos, &this->possibleNbOfContourPoints, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    for (int a0 = 0; a0 < this->possibleNbOfContourPoints; ++a0) {
        thislen = this->contourPoints[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

int ZcmLidarScalaFilteredObjectAttributes::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->objectAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->hiddenStatusAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->dynamicFlagState, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->dynamicFlagProperty, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->relativeTimeOfMeasure, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->positionClosestObjectPointX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->positionClosestObjectPointY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocityX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocityY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocitySigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->relativeVelocitySigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->classification, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->classificationQuality, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->classificationAge, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxSizeSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxOrientation, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxOrientationSigma, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->objectBoxHeight, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointLocation, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointCoordSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->referencePointPositionCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->existenceProbaility, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocityX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocityY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocitySigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->absoluteVelocitySigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->velocityCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->accelerationX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->accelerationY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->accelerationSigmaX, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->accelerationSigmaY, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->accelerationCorrCoeff, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int16_t_decode_array(buf, offset + pos, maxlen - pos, &this->possibleNbOfContourPoints, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    this->contourPoints.resize(this->possibleNbOfContourPoints);
    for (int a0 = 0; a0 < this->possibleNbOfContourPoints; ++a0) {
        thislen = this->contourPoints[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

uint32_t ZcmLidarScalaFilteredObjectAttributes::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    enc_size += __int16_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->possibleNbOfContourPoints; ++a0) {
        enc_size += this->contourPoints[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t ZcmLidarScalaFilteredObjectAttributes::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmLidarScalaFilteredObjectAttributes::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmLidarScalaFilteredObjectAttributes::getHash };

    uint64_t hash = (uint64_t)0x4c13b2dce2c8503aLL +
         ZcmLidarScalaContourPoint::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
