/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmLidarScalaDataScan_hpp__
#define __ZcmLidarScalaDataScan_hpp__

#include <vector>
#include "ZcmService.hpp"
#include "ZcmLidarScalaPoint.hpp"


/**
 * @struct ZcmLidarScalaDataScan
 * @brief Сообщение содержит информацию о всех точках полученных за одно сканирование
 * @var ZcmLidarScalaDataScan::scanNumber
 * @brief - номер скана. Увеличивается с каждым новым сканированием
 * @var ZcmLidarScalaDataScan::rotatingDirection
 * @brief - направление вращения: \n
 * 				 0 - по часовой стрелке \n
 * 				 1 - против часовой стрелки 
 * @var ZcmLidarScalaDataScan::anglePerTick
 * @brief - 1/32 градуса в тике
 * @var ZcmLidarScalaDataScan::anglePerLayer
 * @brief - количество градусов на уровень (Layer)
 * @var ZcmLidarScalaDataScan::scannerHeight
 * @brief - высота на которой расположен сенсор (м)
 * @var ZcmLidarScalaDataScan::nbOfPoints
 * @brief - количество точек в одном сканировании
 * @var ZcmLidarScalaDataScan::scanPoints
 * @brief - массив точек полученных за одно сканирование
 *                         
 *
 */
class ZcmLidarScalaDataScan
{
    public:
        ZcmService service;

        int32_t    scanNumber;

        int32_t    rotatingDirection;

        float      scannerHeight;

        int32_t    nbOfPoints;

        std::vector< ZcmLidarScalaPoint > scanPoints;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr float    anglePerTick = 0.03125;
        static constexpr float    anglePerLayer = 0.8;
        #else
        static const     float    anglePerTick = 0.03125;
        static const     float    anglePerLayer = 0.8;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmLidarScalaDataScan() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmLidarScalaDataScan"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmLidarScalaDataScan::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmLidarScalaDataScan::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmLidarScalaDataScan::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmLidarScalaDataScan::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmLidarScalaDataScan::getTypeName()
{
    return "ZcmLidarScalaDataScan";
}

int ZcmLidarScalaDataScan::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->scanNumber, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->rotatingDirection, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->scannerHeight, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->nbOfPoints, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    for (int a0 = 0; a0 < this->nbOfPoints; ++a0) {
        thislen = this->scanPoints[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

int ZcmLidarScalaDataScan::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->scanNumber, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->rotatingDirection, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->scannerHeight, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->nbOfPoints, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    this->scanPoints.resize(this->nbOfPoints);
    for (int a0 = 0; a0 < this->nbOfPoints; ++a0) {
        thislen = this->scanPoints[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(thislen < 0) return thislen; else pos += thislen;
    }

    return pos;
}

uint32_t ZcmLidarScalaDataScan::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->nbOfPoints; ++a0) {
        enc_size += this->scanPoints[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t ZcmLidarScalaDataScan::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmLidarScalaDataScan::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmLidarScalaDataScan::getHash };

    uint64_t hash = (uint64_t)0x5cec064a23c21efdLL +
         ZcmService::_computeHash(&cp) +
         ZcmLidarScalaPoint::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
