/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmObjectGeometry_hpp__
#define __ZcmObjectGeometry_hpp__

#include "ZcmPoint.hpp"
#include "ZcmPoint.hpp"
#include "ZcmPoint.hpp"
#include "ZcmPoint.hpp"
#include "ZcmPoint.hpp"
#include "ZcmPoint.hpp"


/**
 * @struct ZcmObjectGeometry
 * @brief Содержит информацию о геометрии объекта
 * @var ZcmObjectGeometry::top_left
 * @brief - левая верхняя/дальняя точка
 * @var ZcmObjectGeometry::bottom_left
 * @brief - левая нижняя/ближайшая точка
 * @var ZcmObjectGeometry::top_right
 * @brief - правая верхняя/дальняя точка
 * @var ZcmObjectGeometry::bottom_right
 * @brief - правая нижняя/ближайшая точка
 * @var ZcmObjectGeometry::center
 * @brief - центральная точка объекта (пересечение диагоналей)
 * @var ZcmObjectGeometry::bottom_center
 * @brief - центральная нижняя точка объекта (прямоугольника)
 * @var ZcmObjectGeometry::width
 * @brief - ширина описываемого объекта, в метрах
 * @var ZcmObjectGeometry::height
 * @brief - высота/длина описываемого объекта, в метрах
 *
 */
class ZcmObjectGeometry
{
    public:
        ZcmPoint   top_left;

        ZcmPoint   bottom_left;

        ZcmPoint   top_right;

        ZcmPoint   bottom_right;

        ZcmPoint   center;

        ZcmPoint   bottom_center;

        double     width;

        double     height;

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmObjectGeometry() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmObjectGeometry"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmObjectGeometry::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmObjectGeometry::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmObjectGeometry::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmObjectGeometry::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmObjectGeometry::getTypeName()
{
    return "ZcmObjectGeometry";
}

int ZcmObjectGeometry::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->top_left._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_left._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->top_right._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_right._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->center._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_center._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmObjectGeometry::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->top_left._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_left._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->top_right._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_right._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->center._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->bottom_center._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmObjectGeometry::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->top_left._getEncodedSizeNoHash();
    enc_size += this->bottom_left._getEncodedSizeNoHash();
    enc_size += this->top_right._getEncodedSizeNoHash();
    enc_size += this->bottom_right._getEncodedSizeNoHash();
    enc_size += this->center._getEncodedSizeNoHash();
    enc_size += this->bottom_center._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t ZcmObjectGeometry::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmObjectGeometry::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmObjectGeometry::getHash };

    uint64_t hash = (uint64_t)0xf1cbc1637753a900LL +
         ZcmPoint::_computeHash(&cp) +
         ZcmPoint::_computeHash(&cp) +
         ZcmPoint::_computeHash(&cp) +
         ZcmPoint::_computeHash(&cp) +
         ZcmPoint::_computeHash(&cp) +
         ZcmPoint::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
