/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmServiceVersionData_hpp__
#define __ZcmServiceVersionData_hpp__

#include <string>


/**
 * @struct ZcmServiceVersion
 * @brief Версия программного модуля
 * @var ZcmServiceVersion::MODULE_ALL
 * @brief - Все программные модули
 * @var ZcmServiceVersion::major
 * @brief - Мажорная версия
 * @var ZcmServiceVersion::minor
 * @brief - Минорная версия
 * @var ZcmServiceVersion::dev
 * @brief - Патч-версия
 * @var ZcmServiceVersion::description
 * @brief - Описание
 * @var ZcmServiceVersion::checksum
 * @brief - Контрольная сумма
 *
 */
class ZcmServiceVersionData
{
    public:
        int32_t    major;

        int32_t    minor;

        int32_t    dev;

        std::string description;

        int64_t    checksum;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t   MODULE_ALL = 0;
        #else
        static const     int8_t   MODULE_ALL = 0;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmServiceVersionData() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmServiceVersionData"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmServiceVersionData::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmServiceVersionData::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmServiceVersionData::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmServiceVersionData::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmServiceVersionData::getTypeName()
{
    return "ZcmServiceVersionData";
}

int ZcmServiceVersionData::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->major, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->minor, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->dev, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* description_cstr = (char*) this->description.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &description_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->checksum, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmServiceVersionData::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->major, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->minor, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->dev, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    int32_t __description_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__description_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__description_len__ > maxlen - pos) return -1;
    this->description.assign(((const char*)buf) + offset + pos, __description_len__ - 1);
    pos += __description_len__;

    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->checksum, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmServiceVersionData::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->description.size() + 4 + 1;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t ZcmServiceVersionData::_computeHash(const __zcm_hash_ptr*)
{
    uint64_t hash = (uint64_t)0x8ad7fe065003bba6LL;
    return (hash<<1) + ((hash>>63)&1);
}

#endif
