/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by zcm-gen
 **/

#include <zcm/zcm_coretypes.h>

#ifndef __ZcmServiceVersion_hpp__
#define __ZcmServiceVersion_hpp__

#include <string>
#include "ZcmService.hpp"
#include "ZcmServiceVersionData.hpp"


/**
 * @struct ZcmServiceVersion
 * @brief Сообщение с версией программного модуля
 * @var ZcmServiceVersionRequest::COMPUTER_A
 * @brief - Вычислитель A
 * @var ZcmServiceVersionRequest::COMPUTER_B
 * @brief - Вычислитель B
 * @var ZcmServiceVersionRequest::module
 * @brief - Код программного модуля
 * @var ZcmServiceVersionRequest::module_name
 * @brief - Название программного модуля
 * @var ZcmServiceVersionRequest::computer
 * @brief - Код вычислителя
 * @var ZcmServiceVersionRequest::version
 * @brief - Версия программного модуля
 *
 */
class ZcmServiceVersion
{
    public:
        ZcmService service;

        int32_t    module;

        std::string module_name;

        int8_t     computer;

        ZcmServiceVersionData version;

    public:
        #if __cplusplus > 199711L /* if c++11 */
        static constexpr int8_t   COMPUTER_A = 1;
        static constexpr int8_t   COMPUTER_B = 2;
        #else
        static const     int8_t   COMPUTER_A = 1;
        static const     int8_t   COMPUTER_B = 2;
        #endif

    public:
        /**
         * Destructs a message properly if anything inherits from it
        */
        virtual ~ZcmServiceVersion() {}

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void* buf, uint32_t offset, uint32_t maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline uint32_t getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to reqad while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void* buf, uint32_t offset, uint32_t maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ZcmServiceVersion"
         */
        inline static const char* getTypeName();

        // ZCM support functions. Users should not call these
        inline int      _encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const;
        inline uint32_t _getEncodedSizeNoHash() const;
        inline int      _decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen);
        inline static uint64_t _computeHash(const __zcm_hash_ptr* p);
};

int ZcmServiceVersion::encode(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;
    int64_t hash = (int64_t)getHash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmServiceVersion::decode(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmServiceVersion::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ZcmServiceVersion::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* ZcmServiceVersion::getTypeName()
{
    return "ZcmServiceVersion";
}

int ZcmServiceVersion::_encodeNoHash(void* buf, uint32_t offset, uint32_t maxlen) const
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->module, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    char* module_name_cstr = (char*) this->module_name.c_str();
    thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &module_name_cstr, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int8_t_encode_array(buf, offset + pos, maxlen - pos, &this->computer, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->version._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ZcmServiceVersion::_decodeNoHash(const void* buf, uint32_t offset, uint32_t maxlen)
{
    uint32_t pos = 0;
    int thislen;

    thislen = this->service._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->module, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    int32_t __module_name_len__;
    thislen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &__module_name_len__, 1);
    if(thislen < 0) return thislen; else pos += thislen;
    if((uint32_t)__module_name_len__ > maxlen - pos) return -1;
    this->module_name.assign(((const char*)buf) + offset + pos, __module_name_len__ - 1);
    pos += __module_name_len__;

    thislen = __int8_t_decode_array(buf, offset + pos, maxlen - pos, &this->computer, 1);
    if(thislen < 0) return thislen; else pos += thislen;

    thislen = this->version._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(thislen < 0) return thislen; else pos += thislen;

    return pos;
}

uint32_t ZcmServiceVersion::_getEncodedSizeNoHash() const
{
    uint32_t enc_size = 0;
    enc_size += this->service._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->module_name.size() + 4 + 1;
    enc_size += __int8_t_encoded_array_size(NULL, 1);
    enc_size += this->version._getEncodedSizeNoHash();
    return enc_size;
}

uint64_t ZcmServiceVersion::_computeHash(const __zcm_hash_ptr* p)
{
    const __zcm_hash_ptr* fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ZcmServiceVersion::getHash)
            return 0;
    const __zcm_hash_ptr cp = { p, (void*)ZcmServiceVersion::getHash };

    uint64_t hash = (uint64_t)0x33d0ef8b1ac65077LL +
         ZcmService::_computeHash(&cp) +
         ZcmServiceVersionData::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

#endif
